version: "2.1"

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - /path/to/media/anime:/anime
      - /path/to/media/tvshows:/tvshows
      - /path/to/qbittorrent/downloads/complete:/downloads/complete
    ports:
      - 8989:8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${TRAEFIK_SONARR}`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      - "traefik.http.routers.sonarr.middlewares=whitelist@file"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - /path/to/qbittorrent/downloads/complete:/downloads/complete
      - /path/to/media/movies:/movies
    ports:
      - 7878:7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${TRAEFIK_RADARR}`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      - "traefik.http.routers.radarr.middlewares=whitelist@file"
    restart: unless-stopped
   
   
  readarr: 
    image: linuxserver/readarr:nightly 
    container_name: readarr 
    networks: 
      - proxy 
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ={$TZ} 
    volumes: 
      - ./readarr:/config 
      - /path/to/qbittorrent/downloads/complete:/downloads/complete 
      - /path/to/media/books:/books 
    ports: 
      - 8787:8787 
    labels: 
      - "traefik.enable=true" 
      - "traefik.docker.network=proxy" 
      - "traefik.http.routers.readarr.rule=Host(`${TRAEFIK_READARR}`)" 
      - "traefik.http.routers.readarr.entrypoints=https" 
      - "traefik.http.routers.readarr.tls=true" 
      - "traefik.http.routers.readarr.tls.certresolver=mydnschallenge" 
      - "traefik.http.services.readarr.loadbalancer.server.port=8787" 
      # Watchtower Update 
      - "com.centurylinklabs.watchtower.enable=true" 
      # Ip filtering 
      - "traefik.http.routers.readarr.middlewares=whitelist@file" 
       
       
  bazarr: 
    image: linuxserver/bazarr 
    container_name: bazarr 
    networks: 
      - proxy 
    environment: 
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
    volumes: 
      - ./bazarr:/config 
      - /path/to/media/movies:/movies #optional 
      - /path/to/media/tvshows:/tvshows #optional 
      - /path/to/media/anime:/anime 
    ports: 
      - 6767:6767 
    labels: 
      - "traefik.enable=true" 
      - "traefik.docker.network=proxy" 
      - "traefik.http.routers.bazarr.rule=Host(`${TRAEFIK_BAZARR}`)" 
      - "traefik.http.routers.bazarr.entrypoints=https" 
      - "traefik.http.routers.bazarr.tls=true" 
      - "traefik.http.routers.bazarr.tls.certresolver=mydnschallenge"  
      # Watchtower Update 
      - "com.centurylinklabs.watchtower.enable=true" 
      # Ip filtering 
      - "traefik.http.routers.bazarr.middlewares=whitelist@file" 
    restart: unless-stopped 
     
     
networks: 
  proxy: 
    external: true
