version: "3"

services:
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-advanced
    restart: unless-stopped
    ports:
      - 4040:4040
    volumes:
      - ./data:/var/airsonic
      - /path/to/media/music:/var/music
      - /path/to/media/music/playlists:/var/playlists
      - /path/to/media/podcasts:/var/podcasts
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.entrypoints=https"
      - "traefik.http.routers.airsonic.rule=Host(`${TRAEFIK_AIRSONIC}`)"
      - "traefik.http.routers.airsonic.tls=true"
      - "traefik.http.routers.airsonic.tls.certresolver=mydnschallenge"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      - "traefik.http.routers.airsonic.middlewares=whitelist@file"
      
networks:
  proxy:
    external:
      name: proxy

