version: "3"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    network:
      - proxy
    volumes:
      -./config:/config
    environment:
      - PUID= ${PUID}
      - PGID= ${PGID}
      - TZ= ${America/New_York}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=https"
      - "traefik.http.routers.heimdall.middlewares=whitelist@file"
      - "traefik.http.routers.heimdall.rule=Host(`${TRAEFIK_HEIMDALL}`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.tls.certresolver=mydnschallenge"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      - "traefik.http.routers.bitwarden.middlewares=whitelist@file"
 networks:
   proxy:
     external:true
