version: '3'

services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    hostname: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}  # Requested, set the root's password of MySQL service.
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_LOG_CONSOLE=true
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_AUTO_UPGRADE=1
    networks:
      - nextcloud-net
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      
  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    networks:
      - nextcloud-net
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    hostname: nextcloud
    user: 1000:1000
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      TRUSTED_PROXIES: #localhost 192.168.0.0./24 172.0.0.0/24 127.0.0.0/24
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://${TRAEFIK_NEXTCLOUD}
      OVERWRITEHOST: ${TRAEFIK_NEXTCLOUD}
      REDIS_HOST: nextcloud-redis

    volumes:
      - ./shared/app/data:/var/www/html/data
      - ./shared/app:/var/www/html
    networks:
      - proxy
      - nextcloud-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.rule=Host(`${TRAEFIK_NEXTCLOUD}`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=mydnschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      - "traefik.http.routers.nextcloud.middlewares=whitelist@file"
      
  nextcloud-cron:
    image: nextcloud:apache
    container_name: nextcloud-cron
    restart: always
    volumes:
      - ./shared/app:/var/www/html
      - ./cron:/var/spool/cron/crontabs/
    networks:
      - nextcloud-net
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis 
    labels:
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  nextcloud-net:
  proxy:
    external: true
