api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
  dashboard:
    address: ":8008"

  https:
    address: ":443"

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
 
  file:
    directory: ./rules
    watch: true

certificatesResolvers:
  mydnschallenge:
    acme:
      email: ptgarland@protonmail.com
      storage: ./letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10

log:
  level: INFO
