version: "3.8"
services:
  dashy:
    container_name: Dashy

    image: lissy93/dashy
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=${PUID}
      - GID=${PGID}
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=https"
      - "traefik.http.routers.dashy.rule=Host(`${TRAEFIK_DASHY}`)"
      - "traefik.http.routers.dashy.tls=true"
      - "traefik.http.routers.dashy.tls.certresolver=mydnschallenge"
      - "traefik.http.services.dashy.loadbalancer.server.port=80"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"
      # Ip filtering
      - "traefik.http.routers.dashy.middlewares=whitelist@file"
        # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
networks:
  proxy:
    external:
      name: proxy


